###get all users
GET http://localhost:9090/register/getAllUsers


### Add a user

POST http://localhost:9090/register/addUser
Content-Type: application/json

{
    "username": "testuser500",
    "password": "testpassword",
    "type": "patient"
}

### add patient
POST http://localhost:9090/register/addPatient
Content-Type: application/json

{
    "doctorName": "testDoc2"
}

### login
### Authenticate user
GET http://localhost:9090/register/authenticate?username=watson&password=watson

###get
GET http://localhost:9090/login/authenticate?username=real&password=mad


###get all doctors
GET http://localhost:9090/register/getAllDoctors

### add report
POST http://localhost:9090/reports/addReport
Content-Type: application/json

{
   "username": "watson",
   "platelets": 300000,
   "RBC": 5.5,
   "hemoglobin": 15,
   "date": "2023-12-12"
}

### get reports
GET http://localhost:9090/reports/getReports?username=watson


### upload
curl -X POST -F "image=@C:/Users/Shendre/OneDrive/Pictures/Screenshots/Screenshot (119).png" http://localhost:9090/prescription/upload